window.TRACKER = {
  catalog: {
    COEN212: ["COEN 212", "Digital Systems Design I", 3.5],
    COEN231: ["COEN 231", "Introduction to Discrete Mathematics", 3],
    COEN243: ["COEN 243", "Programming Methodology I", 3.5],
    COEN244: ["COEN 244", "Programming Methodology II", 3],
    COEN311: ["COEN 311", "Computer Organization and Software", 3.5],
    COEN313: ["COEN 313", "Digital Systems Design II", 3.5],
    COEN314: ["COEN 314", "Digital Electronics", 3.5],
    COEN316: ["COEN 316", "Computer Architecture and Design", 3.5],
    COEN317: ["COEN 317", "Microprocessor-Based Systems", 3.5],
    COEN320: ["COEN 320", "Introduction to Real-Time Systems", 3.5],
    COEN330: ["COEN 330", "Applied Machine Learning", 3],
    COEN346: ["COEN 346", "Operating Systems", 3.5],
    COEN352: ["COEN 352", "Data Structures and Algorithms", 3],
    COEN366: ["COEN 366", "Communication Networks and Protocols", 3.5],
    COEN390: ["COEN 390", "Computer Engineering Product Design Project", 3],
    COEN490: ["COEN 490", "Capstone Computer Engineering Design Project", 6],
    ELEC242: ["ELEC 242", "Continuous-Time Signals and Systems", 3],
    ELEC273: ["ELEC 273", "Basic Circuit Analysis", 3.5],
    ELEC342: ["ELEC 342", "Discrete-Time Signals and Systems", 3.5],
    ELEC372: ["ELEC 372", "Fundamentals of Control Systems", 3.5],
    ENGR201: ["ENGR 201", "Professional Practice and Responsibility", 1.5],
    ENGR202: ["ENGR 202", "Sustainable Development and Environmental Stewardship", 1.5],
    ENGR213: ["ENGR 213", "Applied Ordinary Differential Equations", 3],
    ENGR233: ["ENGR 233", "Applied Advanced Calculus", 3],
    ENGR290: ["ENGR 290", "Introductory Engineering Team Design Project", 3],
    ENGR301: ["ENGR 301", "Engineering Management Principles and Economics", 3],
    ENGR371: ["ENGR 371", "Probability and Statistics in Engineering", 3],
    ENGR392: ["ENGR 392", "Impact of Technology on Society", 3],
    ENCS282: ["ENCS 282", "Technical Writing and Communication", 3],
    SOEN341: ["SOEN 341", "Software Process and Practices", 4],
  },
  technical: [
    ["Hardware / electronics / VLSI", [
      ["COEN 413", "Hardware Functional Verification", 3.5],
      ["COEN 451", "VLSI Circuit Design", 4],
      ["ELEC 311", "Electronics I", 3.5],
      ["ELEC 312", "Electronics II", 3.5],
      ["ELEC 321", "Introduction to Semiconductor Materials and Devices", 3.5],
      ["ELEC 413", "Mixed-Signal VLSI for Wireline Communication Systems", 4],
      ["ELEC 423", "Introduction to Analog VLSI", 4],
    ]],
    ["Software and system design", [
      ["COEN 421", "Embedded Systems Design", 4],
      ["COEN 422", "Foundations of Cyber-Physical Systems", 3],
      ["COEN 432", "Applied Machine Learning and Evolutionary Algorithms", 3],
      ["COEN 448", "Software Testing and Validation", 3.5],
      ["COEN 449", "Neural Networks and Machine Learning", 3],
      ["SOEN 342", "Software Requirements and Deployment", 3],
      ["SOEN 343", "Software Architecture and Design", 4],
      ["SOEN 344", "Advanced Software Architecture and Design", 3],
      ["SOEN 357", "User Interface Design", 3],
    ]],
    ["Biological and biomedical", [
      ["COEN 433", "Biological Computing and Synthetic Biology", 3],
      ["COEN 434", "Microfluidic Devices for Synthetic Biology", 3],
      ["ELEC 444", "Medical Image Processing", 3],
      ["ELEC 445", "Biological Signal Processing", 3],
    ]],
    ["Computer science and programming", [
      ["COEN 424", "Programming on the Cloud", 3],
      ["COEN 474", "Quantum Information Processing and Coding", 3],
      ["COMP 335", "Introduction to Theoretical Computer Science", 3],
      ["COMP 353", "Databases", 4],
      ["COMP 371", "Computer Graphics", 4],
      ["COMP 426", "Multicore Programming", 4],
      ["COMP 428", "Parallel Programming", 4],
      ["COMP 442", "Compiler Design", 4],
      ["COMP 451", "Database Design", 4],
      ["COMP 472", "Artificial Intelligence", 4],
      ["COMP 474", "Intelligent Systems", 4],
    ]],
    ["Networks and signal processing", [
      ["COEN 446", "Internet of Things", 3.5],
      ["COEN 447", "Software-Defined Networking", 3],
      ["ELEC 367", "Introduction to Digital Communications", 3.5],
      ["ELEC 442", "Advanced Signal Processing", 3],
      ["ELEC 447", "Video Processing and Recognition", 3],
      ["ELEC 465", "Network Security and Management", 3.5],
      ["ELEC 470", "Broadcast Signal Transmission", 3],
      ["ELEC 472", "Advanced Telecommunication Networks", 3.5],
    ]],
    ["Controls, robotics, avionics", [
      ["AERO 417", "Standards, Regulations and Certification", 3],
      ["AERO 480", "Flight Control Systems", 3.5],
      ["AERO 482", "Avionic Navigation Systems", 3],
      ["AERO 483", "Integration of Avionics Systems", 3],
      ["ELEC 473", "Autonomy for Mobile Robots", 3],
      ["ELEC 481", "Linear Systems", 3.5],
      ["ELEC 482", "System Optimization", 3.5],
      ["ELEC 483", "Real-Time Computer Control Systems", 3.5],
      ["ENGR 472", "Robot Manipulators", 3.5],
    ]],
    ["Other", [
      ["COEN 498", "Topics in Computer Engineering", 3],
      ["ENGR 411", "Special Technical Report", 1],
    ]],
  ],
  natural: [
    ["BIOL 201", "Introductory Biology", 3],
    ["BIOL 202", "General Biology", 3],
    ["BIOL 206", "Elementary Genetics", 3],
    ["BIOL 261", "Molecular and General Genetics", 3],
    ["BIOL 266", "Cell Biology", 3],
    ["CHEM 206", "General Chemistry II", 3],
    ["CHEM 217", "Introductory Analytical Chemistry I", 3],
    ["CHEM 221", "Introductory Organic Chemistry I", 3],
    ["GEOL 206", "Earthquakes, Volcanoes, and Plate Tectonics", 3],
    ["GEOL 208", "The Earth, Moon and the Planets", 3],
    ["PHYS 206", "Waves and Modern Physics", 3],
    ["PHYS 252", "Optics", 3],
    ["PHYS 260", "Introductory Biophysics", 3],
    ["PHYS 273", "Energy and Environment", 3],
    ["PHYS 284", "Introduction to Astronomy", 3],
    ["PHYS 367", "Modern Physics and Relativity", 3],
    ["PHYS 385", "Astrophysics", 3],
    ["PHYS 443", "Quantitative Human Systems Physiology", 3],
    ["PHYS 445", "Principles of Medical Imaging", 3],
  ],
  paths: [
    {
      id: "coop-fall",
      label: "COOP, fall entry",
      note: "Three work terms. COEN 490 runs fall and winter of year 4.",
      terms: [
        ["Fall year 1", ["COEN243", "COEN212", "COEN231", "ENGR213", "ENGR201", "ENGR202"]],
        ["Winter year 1", ["COEN311", "ELEC273", "COEN244", "ENGR233", "ENCS282"]],
        ["Summer year 1", ["ELEC242"]],
        ["Fall year 2", [["work", "coop-work-1"]]],
        ["Winter year 2", ["COEN313", "COEN314", "COEN346", "SOEN341", "ENGR290"]],
        ["Summer year 2", ["COEN330"]],
        ["Fall year 3", ["COEN316", "COEN317", "COEN320", "COEN366", "COEN390"]],
        ["Winter year 3", [["work", "coop-work-2"]]],
        ["Summer year 3", [["work", "coop-work-3"]]],
        ["Fall year 4", ["COEN490", ["gened"], ["elective", "coop-fy4-e1"], ["elective", "coop-fy4-e2"], ["elective", "coop-fy4-e3"]]],
        ["Winter year 4", ["COEN490", ["elective", "coop-wy4-e1"], ["elective", "coop-wy4-e2"], ["elective", "coop-wy4-e3"], ["elective", "coop-wy4-e4"]]],
      ],
    },
    {
      id: "regular-fall",
      label: "Regular, fall entry",
      note: "Summers are empty. COEN 490 runs fall and winter of year 4.",
      terms: [
        ["Fall year 1", ["COEN243", "COEN212", "COEN231", "ENGR213", "ENGR201"]],
        ["Winter year 1", ["COEN311", "ELEC273", "COEN244", "ENGR233", "ENCS282"]],
        ["Summer year 1", []],
        ["Fall year 2", ["ELEC242", "COEN352", "COEN313", "ENGR371", "ENGR202"]],
        ["Winter year 2", ["ELEC342", "COEN330", "ENGR290", "ENGR392", "COEN346"]],
        ["Summer year 2", []],
        ["Fall year 3", ["ENGR301", "COEN316", "COEN314", "COEN320", "SOEN341"]],
        ["Winter year 3", [["gened"], "ELEC372", "COEN317", "COEN366", "COEN390"]],
        ["Summer year 3", []],
        ["Fall year 4", ["COEN490", ["elective", "rf-fy4-e1"], ["elective", "rf-fy4-e2"], ["elective", "rf-fy4-e3"], ["elective", "rf-fy4-e4"]]],
        ["Winter year 4", ["COEN490", ["elective", "rf-wy4-e1"], ["elective", "rf-wy4-e2"], ["elective", "rf-wy4-e3"]]],
      ],
    },
    {
      id: "regular-winter",
      label: "Regular, winter entry",
      note: "Starts in winter. Fall of year 1 is empty. COEN 490 runs fall and winter of year 4.",
      terms: [
        ["Fall year 1", []],
        ["Winter year 1", ["COEN243", "COEN212", "COEN231", "ENGR213", "ENGR201"]],
        ["Summer year 1", ["ELEC273", "COEN244", "ENGR233", "ENCS282"]],
        ["Fall year 2", ["ELEC242", "COEN311", "ENGR371", "COEN352", "ENGR202"]],
        ["Winter year 2", ["ELEC342", "COEN330", "ENGR290", "COEN313", "COEN346"]],
        ["Summer year 2", []],
        ["Fall year 3", ["ENGR392", "COEN316", "COEN314", "COEN320", "SOEN341"]],
        ["Winter year 3", ["ENGR301", "ELEC372", "COEN317", "COEN366", "COEN390"]],
        ["Summer year 3", []],
        ["Fall year 4", ["COEN490", ["gened"], ["elective", "rw-fy4-e1"], ["elective", "rw-fy4-e2"], ["elective", "rw-fy4-e3"]]],
        ["Winter year 4", ["COEN490", ["elective", "rw-wy4-e1"], ["elective", "rw-wy4-e2"], ["elective", "rw-wy4-e3"]]],
      ],
    },
    {
      id: "accelerated",
      label: "Non-COOP, accelerated",
      note: "Shorter sequence. COEN 490 is the two-term capstone in year 3.",
      terms: [
        ["Fall year 1", ["COEN243", "COEN212", "COEN231", "ENGR213", "ENGR201"]],
        ["Winter year 1", ["COEN311", "ELEC273", "COEN244", "ENGR233", "ENCS282"]],
        ["Summer year 2", ["COEN352", "ELEC242", "ENGR202", "ENGR301", ["gened"]]],
        ["Fall year 2", ["COEN346", "COEN313", "ENGR371", "ENGR290", "COEN366"]],
        ["Winter year 2", ["COEN390", "COEN317", "SOEN341", "COEN316"]],
        ["Summer year 3", ["COEN330", "ELEC342", "ELEC372", "ENGR392"]],
        ["Fall year 3", ["COEN490", "COEN314", "COEN320", ["elective", "ac-fy3-e1"], ["elective", "ac-fy3-e2"]]],
        ["Winter year 3", ["COEN490", ["elective", "ac-wy3-e1"], ["elective", "ac-wy3-e2"], ["elective", "ac-wy3-e3"], ["elective", "ac-wy3-e4"]]],
      ],
    },
  ],
};
